# Perceptron Learning

In [3]:
import numpy as np
import matplotlib.pyplot as plt

### Step 1. The Inputs, Weights and Targets as matrices 

$$ X \in R^{n \times d} $$
where : 
$$ n = \text{number of samples/observations} $$
$$ d = \text{number of dimension/features} $$



In [5]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
t = np.array([[0], [0], [0], [1]])
print("Input matrix is :\n", X)
print("++++++++++++++++++++++++++++++++")
print("Target matrix is :\n", t)

Input matrix is :
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
++++++++++++++++++++++++++++++++
Target matrix is :
 [[0]
 [0]
 [0]
 [1]]


In [7]:
Xbias = np.hstack((np.ones((X.shape[0],1)), X))
Wbias = np.zeros((Xbias.shape[1], t.shape[1]))
print("Input matrix with bias is :\n", Xbias)
print("++++++++++++++++++++++++++++++++")
print("Weight matrix with bias is :\n", Wbias)

Input matrix with bias is :
 [[1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
++++++++++++++++++++++++++++++++
Weight matrix with bias is :
 [[0.]
 [0.]
 [0.]]


### Step 4: Computing the output

$$ Z = X \cdot W $$



In [9]:
Z = np.dot(Xbias, Wbias)
print(f"The output before activation is :\n {Z}")

The output before activation is :
 [[0.]
 [0.]
 [0.]
 [0.]]


### Step 5:  Applying Heaviside Threshold

$$ \phi(Z) = \begin{cases} 1 &  Z\geq 0 \\ 0 & Z<0 \end{cases} $$

In [11]:
y = np.where(Z>=0, 1, 0)
print(f"The output after activation is :\n {y}")

The output after activation is :
 [[1]
 [1]
 [1]
 [1]]


## Step 6: Calculating the error

$$E = t - y $$

In [19]:
E = t - y
print(f"The error is :\n {E}")

The error is :
 [[-1]
 [-1]
 [-1]
 [ 0]]


### Step 7: Weight update 

$$ \Delta W = \eta \Epsilon^{T} \cdot X $$

In [20]:
W_update = 1*np.dot(E.T, Xbias)
print(f"The weight update is :\n {W_update.T}")
Wbias += W_update.T
print(f"The updated weights are :\n {Wbias}")


The weight update is :
 [[-3.]
 [-1.]
 [-1.]]
The updated weights are :
 [[-6.]
 [-2.]
 [-2.]]


$ \Delta W = \alpha \epsilon X = \alpha \begin{bmatrix} \epsilon_{11} & \epsilon_{12} \\ \epsilon_{21} & \epsilon_{22} \\
\epsilon_{31} & \epsilon_{32} \\ \epsilon_{41} & \epsilon_{42}\end{bmatrix} ^{T}\cdot 
\begin{bmatrix}
x_{11} & x_{12} & x_{13} & x_{14} & x_{15}\\
x_{21} & x_{22} & x_{23} & x_{24} & x_{25}\\
x_{31} & x_{32} & x_{33} & x_{34} & x_{35}\\
x_{41} & x_{42} & x_{43} & x_{44} & x_{45}
\end{bmatrix} $


$ = \begin{bmatrix} \epsilon_{11} & \epsilon_{21} & \epsilon_{31} & \epsilon_{41} \\ \epsilon_{12} & \epsilon_{22} & \epsilon_{32} & \epsilon_{42} \end{bmatrix} \begin{bmatrix}
x_{11} & x_{12} & x_{13} & x_{14} & x_{15}\\
x_{21} & x_{22} & x_{23} & x_{24} & x_{25}\\
x_{31} & x_{32} & x_{33} & x_{34} & x_{35}\\
x_{41} & x_{42} & x_{43} & x_{44} & x_{45}
\end{bmatrix}$

### 7. Putting Everything Together

In [31]:
epochs = 10
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
t = np.array([[0], [0], [0], [1]])
# print("Input matrix is :\n", X)
# print("++++++++++++++++++++++++++++++++")
# print("Target matrix is :\n", t)
Xbias = np.hstack((np.ones((X.shape[0],1)), X))
Wbias = np.zeros((Xbias.shape[1], t.shape[1]))
# print("Input matrix with bias is :\n", Xbias)
# print("++++++++++++++++++++++++++++++++")
# print("Weight matrix with bias is :\n", Wbias)
for epoch in range(epochs):
    Z = np.dot(Xbias,Wbias)
    y = np.where(Z>=0, 1, 0)
    E = t - y
    #stopping condition 
    if np.all(E == 0):
        print(f"Training completed in {epoch} epochs\ngood weights are :\n {Wbias}")
        break
    W_update = 1*np.dot(E.T, Xbias)
    Wbias += W_update.T
    print(f"Epoch {epoch} and total error is :\n {E.sum()}")

Epoch 0 and total error is :
 -3
Epoch 1 and total error is :
 1
Epoch 2 and total error is :
 1
Epoch 3 and total error is :
 -2
Epoch 4 and total error is :
 1
Training completed in 5 epochs
good weights are :
 [[-2.]
 [ 1.]
 [ 1.]]


### perceptron learning rule function

In [32]:
def perceptron_learning_rule(X, t, epochs=10):
    Xbias = np.hstack((np.ones((X.shape[0],1)), X))
    Wbias = np.zeros((Xbias.shape[1], t.shape[1]))
    for epoch in range(epochs):
        Z = np.dot(Xbias,Wbias)
        y = np.where(Z>=0, 1, 0)
        E = t - y
        if np.all(E == 0):
            print(f"Training completed in {epoch} epochs\ngood weights are :\n {Wbias}")
            return Wbias
        W_update = 1*np.dot(E.T, Xbias)
        Wbias += W_update.T
    print("Training did not converge within the specified epochs")
    return Wbias

W_final = perceptron_learning_rule(X, t, epochs=10)
print(f"Final weights after training:\n {W_final}")

Training completed in 5 epochs
good weights are :
 [[-2.]
 [ 1.]
 [ 1.]]
Final weights after training:
 [[-2.]
 [ 1.]
 [ 1.]]
